### ISSUE TITLE
Use Case: Computer Vision e2e

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#454]
Right now, MLEM doesn't support working with images properly (only as arrays/tensors if we talk about `mlem.api.save(..., sample_data=...)`). Supplying just images there won't work as expected. This is a common scenario that we should support.

End2End CV Use Case would include:

1. Saving a CV model with `mlem.api.save()`
2. Deploying it with `$ mlem deploy`
3. Getting predictions from the deployed application with `$ mlem apply` https://github.com/iterative/mlem/issues/310

Smaller tasks that contributes to this:
- [x] #447  
- [ ] https://github.com/iterative/mlem/issues/509
- [ ] Add docs about this
- [x] Write a blog post
